# Generated by Django 2.2.3 on 2019-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='send_mail',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
