# Generated by Django 2.2.3 on 2019-07-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_booking_send_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('seans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Seans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='active',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='send_mail',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cinema',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
    ]
