# Generated by Django 2.2.3 on 2019-07-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190709_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seans',
            new_name='Seance',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='seans',
            new_name='seance',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='seans',
            new_name='seance',
        ),
    ]
