# Generated by Django 2.2.3 on 2019-07-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190711_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='end_time',
        ),
    ]
