# Generated by Django 2.2.3 on 2019-07-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_seance_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='column_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='row_count',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Room')),
            ],
        ),
    ]
